### ISSUE TITLE
Display of Matrix object not possible

### ISSUE THREAD

**Issue by hhzl** [hpi-swa-teaching/SpreadSheetTool#74] opened 2020-10-23 11:27 UTC
The demo video shows at 2:21

https://www.youtube.com/watch?v=V4OeSZD_Q80&feature=youtu.be

how to inspect
```
m:= Matrix rows: 40 columns: 2 tabulate: #@
```
The video goes over this important step very fast. I assume the menu chosen is 'sheet it'.
However the sheet is empty meanwhile the content of the matrix has a print-it of

```
 a Matrix(1@1 1@2 2@1 2@2 3@1 3@2 4@1 4@2 5@1 5@2 6@1 6@2 7@1 7@2 8@1 8@2 9@1 9@2 10@1 10@2 11@1 11@2 12@1 12@2 13@1 13@2 14@1 14@2 15@1 15@2 16@1 16@2 17@1 17@2 18@1 18@2 19@1 19@2 20@1 20@2 21@1 21@2 22@1 22@2 23@1 23@2 24@1 24@2 25@1 25@2 26@1 26@2 27@1 27@2 28@1 28@2 29@1 29@2 30@1 30@2 31@1 31@2 32@1 32@2 33@1 33@2 34@1 34@2 35@1 35@2 36@1 36@2 37@1 37@2 38@1 38@2 39@1 39@2 40@1 40@2)
```

**Comment by LinqLover** [comment] 2020-10-23 21:04
Thank you again for reporting this issue! :-) Actually, I'm afraid to tell you that this part of the video was kind of a fake, we did not manage to implement this in time. There's already an open issue for this, see #20. There is also a code stub for it in 5beadf2df60844590107af24c801edd5fc37203f but it is not yet ready for prime time. However, you would be very welcome to submit a PR for this feature!

For now, closing this as a duplicate of #20.

**Closed as completed by LinqLover** 2020-10-23 21:04 UTC
Labels: duplicate

**Comment by hhzl** [comment] 2020-10-24 05:24
Thank you for the link to the code stub. I will have a look at it. I suggest that you also have a matrix example in the 'examples package' with a note that it is not implemented yet.

**Comment by LinqLover** [comment] 2020-10-24 18:26
I'm sorry, the code stub does not even work at the moment. I don't think we could provide any valuable example for this at the moment ...
